services:
  backend-flask:
    image: adityaapte/lms-backend:1.0.0
    pull_policy: always
    ports:
      - "4000:4000"
    environment: 
      - FLASK_ENV=development 
      - FLASK_APP=app.py 
      - NEW_RELIC_LICENSE_KEY=eu01x9b6299ec63cfa5dd49585e08e6ee264NRAL 
      - NEW_RELIC_APP_NAME=${NEW_RELIC_APP_NAME:-LMS System - Backend} 
      - NEW_RELIC_ENVIRONMENT=${NEW_RELIC_ENVIRONMENT:-production}
    networks:
      - app-network

  frontend:
    image: adityaapte/lms-frontend:1.0.0
    pull_policy: always
    ports:
      - "80:80"
    depends_on:
      - backend-flask
    networks:
      - app-network

networks:
  app-network:
    driver: bridge